---
- hosts: webservers
  become: true
  tasks:
    - name: Installing apache on webserver
      yum:
        name: httpd
        state: present
      
    - name: Starting apache service
      service:
        name: httpd
        state: started
        enabled: true
        
    - name: copy index.html
      copy:
        src: index.html
        dest: /var/www/html
   
